blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'


urlpatterns = [
    path('', views.all_blogs, name='blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
    path('blogs/', views.all_blogs, name='all_blogs'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    subject = models.CharField(max_length=255)
    timestamp = models.DateField()
    message = models.TextField()

    def __str__(self):
        return self.subject

portfolio/models.py
from django.db import models


class Project(models.Model):
    FRONTEND = 'Frontend'
    BACKEND = 'Backend'
    FULLSTACK = 'Fullstack'
    OTHER = 'Other'
    CATEGORY_CHOICES = ( 
        (FRONTEND, 'FE'),
        (BACKEND,'BE'),
        (FULLSTACK, 'FS'),
        (OTHER, 'OT'),
    )   

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10, default=OTHER)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.order_by('-timestamp')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from .models import Project
from blog.models import Blog


SKILLS = {
    'prog_langs': {
        'primary': ['<b>Python</b>', '<b>Java</b>', 'JavaScript (ES6+)', 'C/C++'],
        'secondary': ['<b>HTML/5</b>', '<b>CSS/3</b>', 'Bootstrap', 'Materialize'],
        'other': ['XML', 'PHP', 'JSON', 'Unix/Linux/<b>Bash</b>', 'MATLAB']
   },
    'frameworks': {
        'mvc': ['<b>Angular/Angular.js</b>', '<b>Django</b>', 'Flask', 'React'],
        'js': ['<b>TypeScript</b>', 'JQuery', 'D3.js', 'Nodejs/npm', 'Express.js'],
        'testing': ['Appium', 'Selenium']
    },
    'databases': {
        'primary': ['PostgreSQL', 'MongoDB', 'Firebase'],
        'secondary': ['MySQL', 'SQLite']
    },
    'environments': {
        'testing': ['JUnit', 'TestNG', 'unittest (python)'],
        'ci-cd': ['Jenkins', 'Jira', 'Git', 'SVN'],
        'virtual': ['VM/Containers: VirtualBox', 'VMWare', '<b>Docker Container</b>', 'Kubernetes Pods'],
        'other': ['<b>Vi/Vim</b>', 'Eclipse', 'Sublime', '<b>Atom</b>', 'LaTex']
    }
}

EXPERIENCES = [
    {
        'title': 'Software Engineer',
        'company_name': 'Datera, Inc.',
        'start_date': 'April 2017',
        'end_date': 'Present',
        'responsibilities': [
            ('Development for internal framework APIs to communicate with '
             'clusters/storage nodes.'),
            ('Owned 2-3 core product features from a QA & Release standpoint; '
             'Point-of-Contact for the life-cycle of nodes/clusters and '
             'node-data mappings.'),
            ('Enforced good ethics & clean coding standards using PEP-8, '
             'Flake8, Pylint, and TDD; daily peer-code review, bug '
             'regression/triaging & automation, OOP & architectural design '
             'within internal product libraries.'),
            ('Proficient in iSCSI, cloud clusters, iops, replication, and '
             'application/data driven practices; worked in various development'
             ' stacks, data layers, OS-level architectures, Cloud-related '
             'infrastructures: clusters, storage nodes, iops, iSCSI layer, '
             'data-inconsistencies, data-replication, and data-orchestration.')
        ]
    },
    {
        'title': 'Software Developer',
        'company_name': 'Wells Fargo Bank',
        'start_date': 'July 2016',
        'end_date': 'March 2017',
        'responsibilities': [
            ('Design, architect, and develop an automation testing framework '
             'from the ground-up using Java/EE, Appium, Selenium, JUnit, '
             'TestNG, SVN, Maven.'),
            ('Leveraged the framework being developed to create and '
             'continuously integrate automated scripts on browsers, Android, '
             'iOS, Windows mobile devices for the Wells Fargo banking app.'),
            ('Helped Wells Fargo cut down on manual QA cost through the Testing'
             '& Automation Framework.'),
            ('Joined with one other junior member and expanded the team from '
             'size two to ten by the end.')
        ]
    },
    {
        'title': 'Developer Intern',
        'company_name': 'Xactly Corp.',
        'start_date': 'January 2016',
        'end_date': 'June 2016',
        'responsibilities': [
            ('Developed a full-stack web-based application for form creation, '
             'management, submission, and result visualization which features '
             'a dynamic UI form generator; designed to meet the demands of '
             'Xactly Administrators, Managers, and Employees.'),
            ('Agile development using MEAN stack with JQuery, MySQL.'),
            ('Expedited development process using Agile, scrum and burn-up '
             'charts under Xactly’s mentorship.')
        ]
    },
    {
        'title': 'Technician Lead & Supervisor',
        'company_name': 'ResNet (UCSC)',
        'start_date': 'September 2013',
        'end_date': 'April 2016',
        'responsibilities': [
            ('Worked as a full-time student to interview, train, and manage '
             '20+ university staff members in IT computer repair, network '
             'troubleshooting, and customer relationship management.'),
            ('Expedited and delegated the repairs of dozens of computers '
             'within the office with various issues including virus '
             'infections, re-formats, and replacing malfunctioning hardware '
             'on a daily basis.'),
            ('Effectively resolved hundreds of campus wide network outages '
             'using tools and skills that identified disruptive network '
             'behaviors.')
        ]
    }
];


all_projects = Project.objects.all()
projects = None
projects2 = all_projects[:6] 
blogs = Blog.objects.order_by('-timestamp')[:6]

def index(request):
    content = parse_skills_content()
    paginator = Paginator(all_projects, 6) # Show 3 projects per page
    page = request.GET.get('page')
    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        projects = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        projects = paginator.page(paginator.num_pages)

    data_dict = {
        'projects': projects,
        'projects2': projects2,
        'blogs': blogs,
        'langs': content['languages'],
        'frameworks': content['frameworks'],
        'databases': content['databases'],
        'environments': content['environments'],
        'experiences': EXPERIENCES[:2],
        'experiences2': EXPERIENCES[2:]
    }
    return render(request, 'portfolio/index.html', data_dict)

def all_blogs(request):
    blogs = Blog.objects.order_by('-timestamp')
    data_dict = {
        'blogs': blogs
    }
    return render(request, 'portfolio/blogs.html', data_dict)

def group_items(items):
    rotate_str = ''
    n = len(items)
    if n == 1:
        return items[0]
    for i in range(n-1):
        item = items[i]
        rotate_str += (items[i] + ' | ')
    rotate_str += items[n-1]
    return rotate_str

def parse_langs():
    langs = ''
    langs += group_items(SKILLS['prog_langs']['primary']) + ','
    langs += group_items(SKILLS['prog_langs']['secondary']) + ','
    langs += group_items(SKILLS['prog_langs']['other'])
    return langs

def parse_frameworks():
    frameworks = ''
    frameworks += group_items(SKILLS['frameworks']['mvc']) + ','
    frameworks += group_items(SKILLS['frameworks']['js']) + ','
    frameworks += group_items(SKILLS['frameworks']['testing'])
    return frameworks

def parse_envs():
    environments = ''
    environments += group_items(SKILLS['environments']['testing']) + ','
    environments += group_items(SKILLS['environments']['ci-cd']) + ','
    environments += group_items(SKILLS['environments']['virtual']) + ','
    environments += group_items(SKILLS['environments']['other'])
    return environments

def parse_dbs():
    databases = ''
    databases += group_items(SKILLS['databases']['primary']) + ','
    databases += group_items(SKILLS['databases']['secondary']) + ','
    return databases

def parse_skills_content():
    content = {}
    # build primary langs string for text-rotating ul li tags
    content['languages'] = parse_langs()
    # build frameworks string for text-rotating ul li tags
    content['frameworks'] = parse_frameworks()
    # build environments string for text-rotating ul li tags
    content['environments'] = parse_envs()
    # build databases string for text-rotating ul li tags
    content['databases'] = parse_dbs()
    return content

portfolio/templates/portfolio/about.html
{% load static %}

<!-- section about -->
<div class="container">
    <!-- section title -->
    <h2 class="section-title wow fadeInUp">About Me</h2>
    <div class="spacer" data-height="60"></div>
    <div class="row">
        <div class="col-md-3">
            <div class="text-center text-md-left">

                <div class="portfolio-wrapper">
                    <!-- portfolio item -->
                    <a href="#gallery-1" class="gallery-link">
                        <div class="thumb">
                            <!-- avatar image -->
                            <img src="{% static 'portfolio/images/about_photo.jpg' %}" alt="Me" />
                            <div class="mask"></div>
                        </div>
                    </a>

                    <div id="gallery-1" class="gallery mfp-hide">
    
                        <a href="{% static 'portfolio/images/about_photo.jpg' %}" data-source="http://500px.com/photo/32736307" title="Me & Autumn Driving" style="width:193px;height:125px;">
                            <img src="{% static 'portfolio/images/autumn.jpg' %}" width="193" height="125">
                        </a>
                        <a href="{% static 'portfolio/images/autumn.jpg' %}" data-source="http://500px.com/photo/32736307" title="Autumn" style="width:193px;height:125px;">
                            <img src="{% static 'portfolio/images/autumn.jpg' %}" width="193" height="125">
                        </a>
                        <a href="{% static 'portfolio/images/anika.jpg' %}" data-source="http://500px.com/photo/32554131" title="Anika" style="width:82px;height:125px;">
                            <img src="{% static 'portfolio/images/anika.jpg' %}" width="82px" height="125">
                        </a>
                    </div>
                </div>
            </div>
            <div class="spacer d-md-none d-lg-none" data-height="30"></div>
        </div>
        <div class="col-md-9 triangle-left-md triangle-top-sm">
            <div class="rounded bg-dark shadow-light padding-30">
                <div class="row">
                    <div class="col-md-6">
                        <!-- about text -->
                        <p>I am Justin Barros, Software Engineer from the Bay Area, California. I am a Python/Java Developer, and dog owner.</p>
                        <!--
                        <div class='row'>
                            <div class='col-sm-6'></div>
                            <div class='col-sm-6'></div>
                        </div>
                        -->
                        <div class="mt-3">
                            <a href="{% static 'portfolio/JB_Resume.pdf' %}" class="btn btn-default" download>Download Resume/CV</a>
                        </div>
                        <div class="spacer d-md-none d-lg-none" data-height="30"></div>
                    </div>
                    <div class="col-md-6">
                        <!-- skill item -->
                        <div class="skill-item">
                            <div class="skill-info clearfix">
                                <h4 class="float-left mb-3 mt-0">Development/Engineering</h4>
                                <span class="float-right">75%</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar data-background" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="70" data-color="#FFD15C">
                                </div>
                            </div>
                            <div class="spacer" data-height="20"></div>
                        </div>
                        <!-- skill item -->
                        <div class="skill-item">
                            <div class="skill-info clearfix">
                                <h4 class="float-left mb-3 mt-0">Dev-Ops</h4>
                                <span class="float-right">80</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar data-background" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="85" data-color="#FF4C60">
                                </div>
                            </div>
                            <div class="spacer" data-height="20"></div>
                        </div>
                        <!-- skill item -->
                        <div class="skill-item">
                            <div class="skill-info clearfix">
                                <h4 class="float-left mb-3 mt-0">QA-Automation</h4>
                                <span class="float-right">95%</span>
                            </div>
                            <div class="progress">
                                <div class="progress-bar data-background" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="95" data-color="#6C6CE5">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row end -->

    <div class="spacer" data-height="70"></div>
    <br/><br/>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <!-- fact item -->
            <div class="fact-item">
                <span class="icon icon-cup"></span>
                <div class="details">
                    <h3 class="mb-0 mt-0 number"><em>Enjoys</em></h3>
                    <p class="mb-0">Problem Solving!</p>
                </div>
            </div>
            <div class="spacer d-md-none d-lg-none" data-height="30"></div>
        </div>
        <div class="col-md-3 col-sm-6">
            <!-- fact item -->
            <div class="fact-item">
                <i class="icon fa fa-gamepad"></i>
                <div class="details">
                    <h3 class="mb-0 mt-0 number"><em>Loves</em></h3>
                    <p class="mb-0">Video Games!</p>
                </div>
            </div>
            <div class="spacer d-md-none d-lg-none" data-height="30"></div>
        </div>
        <div class="col-md-3 col-sm-6">
            <!-- fact item -->
            <div class="fact-item">
                <span class="icon icon-people"></span>
                <div class="details">
                    <h3 class="mb-0 mt-0 number"><em>Team</em></h3>
                    <p class="mb-0">Player!</p>
                </div>
            </div>
            <div class="spacer d-md-none d-lg-none" data-height="30"></div>
        </div>
        <div class="col-md-3 col-sm-6">
            <!-- fact item -->
            <div class="fact-item">
                <span class="icon icon-plane"></span>
                <div class="details">
                    <h3 class="mb-0 mt-0 number"><em>Traveled</em></h3>
                    <p class="mb-0">5 Countries</p>
                </div>
            </div>
        </div>
    </div>
</div>

portfolio/templates/portfolio/blog_preview.html
{% load static %}
{% get_static_prefix as STATIC_URL %}
<!-- section blog -->
<div class="container">
    <!-- section title -->
    <h2 class="section-title wow fadeInUp">Latest Posts</h2>
    <div class="spacer" data-height="60"></div>
    <div class="row blog-wrapper">
        {% if blogs %}
        {% for blog in blogs %}
        <div class="col-md-4">
            <!-- blog item -->
            <div class="blog-item rounded bg-dark shadow-light wow fadeIn">
                <div class="thumb">
                    <a href="#"><span class="category">Blog</span></a>
                    <a href='{% url "blog:detail" blog.id %}'><img src="{{ STATIC_URL }}portfolio/images/poly{{ forloop.counter }}.jpg" alt="blog-title" /></a>
                </div>
                <div class="details">
                    <h4 class="my-0 title"><a href='{% url "blog:detail" blog.id %}'>{{ blog.subject }}</a></h4>
                    <ul class="list-inline meta mb-0 mt-2">
                        <li class="list-inline-item">{{ blog.timestamp|date:'F jS Y' }}</li>
                        <li class="list-inline-item">Justin</li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}

        <!-- more button -->
        <div class="col text-center mt-4">
            <a href="{% url 'all_blogs' %}" class="btn btn-default"><i class="fas fa-spinner"></i> All Blogs</a>
        </div>

        {% else %}
        <h2>No Blogs Created</h2>
        {% endif %} 
    </div>
</div>

portfolio/templates/portfolio/blogs.html
<html>
{% load static %}
{% get_static_prefix as STATIC_URL %}

<head>
    <!-- Compiled and minified CSS -->
    <!-- STYLESHEETS -->
    <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'portfolio/css/all.min.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'portfolio/css/simple-line-icons.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'portfolio/css/slick.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'portfolio/css/animate.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'portfolio/css/magnific-popup.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}" type="text/css" media="all">
</head>

<body class="dark">

    <!-- Preloader -->
    <div id="preloader">
        <div class="outer">
            <!-- Google Chrome -->
            <div class="infinityChrome"><div></div></div>
            <!-- Safari and others -->
            <div class="infinity"><div><span></span></div></div>
            <!-- Stuff -->
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" class="goo-outer">
                <defs>
                    <filter id="goo">
                        <feGaussianBlur in="SourceGraphic" stdDeviation="6" result="blur" />
                        <feColorMatrix in="blur" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
                        <feBlend in="SourceGraphic" in2="goo" />
                    </filter>
                </defs>
            </svg>
        </div>
    </div>

    <!-- mobile header -->
    <header class="mobile-header-1">
        <div class="container">
            <!-- menu icon -->
            <div class="menu-icon d-inline-flex mr-4">
                <button><span></span></button>
            </div>

            <!-- logo image -->
            <div class="site-logo">
                <a href="/"><img src="{{ STATIC_URL }}portfolio/images/logo_transparent.png" alt="JabHax" /></a>
            </div>
        </div>
    </header>

    <!-- desktop header -->
    <header class="desktop-header-1 d-flex align-items-start flex-column">

        <!-- logo image -->
        <div class="site-logo">
            <a href="/"><img src="{{ STATIC_URL }}portfolio/images/logo_transparent.png" alt="JabHax" /></a>
        </div>

        <!-- main menu -->
        <nav>
            <ul class='vertical-menu'>
                <li class='active'><a href='/#'><i class='icon-home'></i>Home</a></li>
                <li><a href='/blogs#blog'><i class='icon-note'></i>Blog</a></li>
                <li><a href='/blogs#contact'><i class='icon-bubbles'></i>Contact</a></li>
            </ul>
        </nav>

        <!-- site footer -->
        <div class='footer'>
            <!-- copyright text -->
            <span class='copyright'>© 2020 JabHax.</span>
        </div>
    </header>

    <!-- main layout -->
    <main class='content'>
        <section id='home' class='home d-flex align-items-center'>{% include 'portfolio/home.html' %}</section>
        <section id='blog' class='blog'>{% include 'blog/all_blogs.html' %}</section>
        <section id='contact' class='contact'>{% include 'portfolio/contact.html' %}</section>
    </main>
    <!-- Go to top button -->
    <a href='#' id='return-to-top'><i class='fas fa-arrow-up'></i></a>

    <!-- SCRIPTS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'portfolio/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'portfolio/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'portfolio/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'portfolio/js/popper.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'portfolio/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'portfolio/js/infinite-scroll.min.js' %}"></script>
    <script src="{% static 'portfolio/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'portfolio/js/slick.min.js' %}"></script>
    <script src="{% static 'portfolio/js/contact.js' %}"></script>
    <script src="{% static 'portfolio/js/validator.js' %}"></script>
    <script src="{% static 'portfolio/js/wow.min.js' %}"></script>
    <script src="{% static 'portfolio/js/morphext.min.js' %}"></script>
    <script src="{% static 'portfolio/js/parallax.min.js' %}"></script>
    <script src="{% static 'portfolio/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'portfolio/js/custom.js' %}"></script>

</body>
</html>

portfolio/templates/portfolio/contact.html
<!-- section contact -->
<div class="container">
    <!-- section title -->
    <h2 class="section-title wow fadeInUp">Get In Touch</h2>
    <div class="spacer" data-height="60"></div>
    <div class="row">
        <div class="col-md-4">
            <!-- contact info -->
            <div class="contact-info">
                <h3 class="wow fadeInUp">Let's talk about everything!</h3>
                <p class="wow fadeInUp">Don't like forms? Send me an <a href="mailto:justiniabarros@gmail.com">email</a>. 👋</p>
            </div>
            <ul class='social-icons'>
                <li class="wow fadeInUp" style="list-style: none;">
                    <a href="mailto:justiniabarros@gmail.com"><i class='fa fa-envelope'></i></a>  JustinIABarros@gmail.com
                </li>
                <li class="wow fadeInUp" style="list-style: none;">
                    <a href="tel:5109789953"<i class='fa fa-phone'></i></a>  510-978-9953
                </li>
                <li class="wow fadeInUp" style="list-style: none;">
                    <a href="https://www.google.com/maps/place/Pleasanton,+CA/@37.6615264,-121.9469882,12z/data=!3m1!4b1!4m5!3m4!1s0x808fe9a261ba755f:0xb3ab6847e1ea7d16!8m2!3d37.6604484!4d-121.8757968"<i class='fa fa-map-marker-alt'></i></a>  Pleasanton, California
                </li>
            </ul>
        </div>
        <div class="col-md-8">
            <!-- Contact Form -->
            <form id="contact-form" class="contact-form mt-6" method="post" action="form/contact.php">
                <div class="messages"></div>
                <div class="row">
                    <div class="column col-md-6">
                        <!-- Name input -->
                        <div class="form-group">
                            <input type="text" class="form-control" name="InputName" id="InputName" placeholder="Your name" required="required" data-error="Name is required.">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="column col-md-6">
                        <!-- Email input -->
                        <div class="form-group">
                            <input type="email" class="form-control" id="InputEmail" name="InputEmail" placeholder="Email address" required="required" data-error="Email is required.">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="column col-md-12">
                        <!-- Email input -->
                        <div class="form-group">
                            <input type="text" class="form-control" id="InputSubject" name="InputSubject" placeholder="Subject" required="required" data-error="Subject is required.">
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>

                    <div class="column col-md-12">
                        <!-- Message textarea -->
                        <div class="form-group">
                            <textarea name="InputMessage" id="InputMessage" class="form-control" rows="5" placeholder="Message" required="required" data-error="Message is required."></textarea>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                </div>
                <button type="submit" name="submit" id="submit" value="Submit" class="btn btn-default">Send Message</button><!-- Send Button -->
            </form>
            <!-- Contact Form end -->
        </div>
    </div>
</div>

portfolio/templates/portfolio/desktop_header.html
<header class="desktop-header-1 d-flex align-items-start flex-column">
    <!-- logo image -->
    <div class="site-logo">
        <a href="/"><img src="{{ STATIC_URL }}portfolio/images/logo_transparent.png" alt="JabHax" /></a>
    </div>

    <!-- main menu -->
    <nav>
        <ul class='vertical-menu'>
            <li class='active'><a href='#'><i class='icon-home'></i>Home</a></li>
            <li><a href='/#about' data-target='#'><i class='icon-user-following'></i>About</a></li>
            <li><a href='/#skills'><i class='icon-fire'></i>Skills</a></li>
            <li><a href='/#education'><i class='icon-graduation'></i>Education</a></li>
            <li><a href='/#experience'><i class='icon-briefcase'></i>Experience</a></li>
            <li><a href='/#projects'><i class='icon-layers'></i>Projects</a></li>
            <li><a href='/#blog'><i class='icon-note'></i>Blog</a></li>
            <li><a href='/#contact'><i class='icon-bubbles'></i>Contact</a></li>
        </ul>
    </nav>

    <!-- site footer -->
    <div class='footer'>
        <!-- copyright text -->
        <span class='copyright'>© 2020 JabHax.</span>
    </div>
</header>

portfolio/templates/portfolio/education.html
<!-- section education -->
<div class="container">
    <!-- section title -->
    <h2 class="section-title wow fadeInUp">Education</h2>
    <div class="spacer" data-height="60"></div>
    <br/>
    <div class="row d-flex justify-content-center align-self-center">
        <div class='col-md-12'>
            <!-- timeline wrapper -->
            <div class="timeline edu bg-dark rounded shadow-light padding-30 overflow-hidden">
                <!-- timeline item -->
                <div class="timeline-container wow fadeInUp">
                    <div class="content">
                        <span class="time">September 2012 ~ June 2016</span>
                        <h3 class="title">Bachelors of Science in Computer Science.</h3>
                        <h3 class="title">University Of California, Santa Cruz</h3>
                    </div>
                </div>
                <!-- main line -->
                <span class="line"></span>
            </div>
        </div>
    </div>
</div>

portfolio/templates/portfolio/mobile_header.html
<header class="mobile-header-1">
    <div class="container">
        <!-- menu icon -->
        <div class="menu-icon d-inline-flex mr-4">
            <button><span></span></button>
        </div>

        <!-- logo image -->
        <div class="site-logo">
            <a href="/"><img src="{{ STATIC_URL }}portfolio/images/logo_transparent.png" alt="JabHax" /></a>
        </div>
    </div>
</header>

portfolio/templates/portfolio/preloader.html
<div id="preloader">
    <div class="outer">
        <!-- Google Chrome -->
        <div class="infinityChrome"><div></div></div>
        <!-- Safari and others -->
        <div class="infinity"><div><span></span></div></div>
        <!-- Stuff -->
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" class="goo-outer">
            <defs>
                <filter id="goo">
                    <feGaussianBlur in="SourceGraphic" stdDeviation="6" result="blur" />
                    <feColorMatrix in="blur" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
                    <feBlend in="SourceGraphic" in2="goo" />
                </filter>
            </defs>
        </svg>
    </div>
</div>